# Generated by Django 4.2.23 on 2025-09-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
    ]
